### ISSUE TITLE
Windows installation instruction using WinGet does not install all required dependencies

### ISSUE THREAD

**Issue by bkhouri** [swiftlang/swift-org-website#839]
## Describe the bug

The instructions on [Installation via Windows Package Manager](https://www.swift.org/install/windows/winget/) does not install all required dependencies.

## To Reproduce

Steps to reproduce the behaviour:

1. Follow the step outlined on https://www.swift.org/install/windows/winget/ to install Swift on Windows using `winget`. A screenshot of the instructions can be found below.
2. Open Visual Studio 2022
3. Open Visual Studio 2022 built-in terminal
4. run the following
```
mkdir mySwiftPackage
cd mytest
swift package init
swift build
```

At the time of writing this issue, the page content is: 

 <img width="922" alt="Screenshot 2024-10-29 at 10 46 28 AM" src="https://github.com/user-attachments/assets/c37dae9c-735b-4dec-8b79-9f714e38495e">

- The code block in step 2 is `winget install --id Microsoft.VisualStudio.2022.Community --exact --force --custom "--add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"`
- The code block in step 3 is `winget install --id Swift.Toolchain -e`

## Expected behavior

The `swift build` is successful, so either:
- the documentation is updated to include instructions on installing all required dependencies
- the `winget` install command should automatically start installation of the required dependencies

## Actual behavior

The build is unsuccessful as some dependencies do not appear to be installed. 

```
PS C:\Users\bkhouri\Documents\git_win\sample_proj> swift build
error: 'sample_proj': Invalid manifest (compiled with: ["C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\bin\\swiftc.exe", "-vfsoverlay", "C:\\Users\\bkhouri\\AppData\\Local\\Temp\\TemporaryDirectory.97ZPCH\\vfs.yaml", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\lib\\swift\\pm\\ManifestAPI", "-lPackageDescription", "-sdk", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\SDKs\\Windows.sdk\\", "-libc", "MD", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\aarch64", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\aarch64", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\Testing-development\\usr\\lib\\swift\\windows", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\Testing-development\\usr\\lib\\swift\\windows\\aarch64", "-use-ld=lld", "-swift-version", "6", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\lib\\swift\\pm\\ManifestAPI", "-package-description-version", "6.0.0", "C:\\Users\\bkhouri\\Documents\\git_win\\sample_proj\\Package.swift", "-o", "C:\\Users\\bkhouri\\AppData\\Local\\Temp\\TemporaryDirectory.ZrF1QN\\sample_proj-manifest.exe"])
error: link command failed with exit code 1 (use -v to see invocation)
lld-link: error: could not open 'msvcrt.lib': no such file or directory
lld-link: error: could not open 'oldnames.lib': no such file or directory
lld-link: error: could not open 'msvcprt.lib': no such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: 'sample_proj': Invalid manifest (compiled with: ["C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\bin\\swiftc.exe", "-vfsoverlay", "C:\\Users\\bkhouri\\AppData\\Local\\Temp\\TemporaryDirectory.pQzFha\\vfs.yaml", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\lib\\swift\\pm\\ManifestAPI", "-lPackageDescription", "-sdk", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\SDKs\\Windows.sdk\\", "-libc", "MD", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\aarch64", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\aarch64", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\Testing-development\\usr\\lib\\swift\\windows", "-L", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Platforms\\6.0.2\\Windows.platform\\Developer\\Library\\Testing-development\\usr\\lib\\swift\\windows\\aarch64", "-use-ld=lld", "-swift-version", "6", "-I", "C:\\Users\\bkhouri\\AppData\\Local\\Programs\\Swift\\Toolchains\\6.0.2+Asserts\\usr\\lib\\swift\\pm\\ManifestAPI", "-package-description-version", "6.0.0", "C:\\Users\\bkhouri\\Documents\\git_win\\sample_proj\\Package.swift", "-o", "C:\\Users\\bkhouri\\AppData\\Local\\Temp\\TemporaryDirectory.e6uuwx\\sample_proj-manifest.exe"])
error: link command failed with exit code 1 (use -v to see invocation)
lld-link: error: could not open 'msvcrt.lib': no such file or directory
lld-link: error: could not open 'oldnames.lib': no such file or directory
lld-link: error: could not open 'msvcprt.lib': no such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Screenshots

<img width="1424" alt="Screenshot 2024-10-29 at 10 52 35 AM" src="https://github.com/user-attachments/assets/8a54d5b7-c917-454f-b263-f6e8c8887937">

### Desktop

- OS: Windows
- Browser: Edge
- Version: Windows 11, running Microsoft Edge Version 130.0.2849.56 (Official build) (arm64) 

### Smartphone
N/A

### If possible, minimal yet complete reproducer code (or link to code)
See "Steps to Reproduce" above

### Swift.org version/commit hash
Access https://www.swift.org on Tuesday October 29 at 11:00AM ET (it's as close of a version/commit I can get :) )

## Additional context
Adding one of these solved the issue. 

The default steps installed MSCV X86_64 toolchain, while I was running Windows on ARM.  Adding the following components allows the build the succeed.
<img width="395" alt="Screenshot 2024-10-30 at 8 41 56 AM" src="https://github.com/user-attachments/assets/d1245673-ba33-49a0-bd78-4d9f249b7391">

**Comment by dschaefer2** [comment]
I've seen those errors when building with the Swift ARM toolchain without the MSVC ARM toolchains being installed.

**Comment by compnerd** [comment]
The piece that was missing is `--add Microsoft.VisualStudio.Component.VC.Tools.ARM64`. I'm fine with adding that to the instructions, but then people might complain about installing "unnecessary" components, but this seems reasonable for enabling cross-compilation.

**Comment by shahmishal** [comment]
@compnerd or @bkhouri can you create a PR to update the instructions on the install page?
